# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'
platform :ios, '9.0'

target 'QrNfcV3' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    swift_version = "4.0"
    pod "AdtagScanProximity", '3.0-RC23'

    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end

end
