source 'https://github.com/CocoaPods/Specs.git'
source 'git@forge.adtag.eu:ConnecthingsSDK/Specs.git'

platform :ios, '8.0'

target 'beaconAlertStarter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod "ATLocationBeacon", '~> 2.6-RC3'
  # Pods for beaconAlertStarter


  target 'beaconAlertStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'beaconAlertStarterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
