source 'https://github.com/CocoaPods/Specs.git'
source 'git@forge.adtag.eu:ConnecthingsSDK/Specs.git'

platform :ios, '8.0'

target 'NotificationStarter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  "ATLocationBeacon", '~> 2.6-RC3'

end
