platform :ios, '8.0'

target 'QuickComplete' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  

  # Pods for beaconAlertStarter


  target 'QuickCompleteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickCompleteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
