source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'
platform :ios, '8.0'

target 'QuickStart' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod "ATLocationBeacon", '~> 2.8'  # Pods for beaconAlertStarter

  target 'QuickStartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickStartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
