source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'
platform :ios, '9.0'

target 'QuickComplete' do
	# Uncomment this line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!	

	pod "AdtagLocationDetection", '3.1.3'
	target 'QuickCompleteTests' do
		inherit! :search_paths
	end

	target 'QuickCompleteUITests' do
		inherit! :search_paths
	end

    post_install do |installer|
        installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
                configuration.build_settings['SWIFT_VERSION'] = "4.1"
            end
        end
    end

end
