source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'

platform :ios, '9.0'

target 'beaconAlertComplete' do
	use_frameworks!
	pod "AdtagLocationBeacon", '~> 3.0-RC7'

	target 'beaconAlertCompleteTests' do
		inherit! :search_paths
	end
	
	target 'beaconAlertCompleteUITests' do
		inherit! :search_paths
	end
end
