source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'
platform :ios, '9.0'

target 'QuickStart' do
	# Uncomment this line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!

	pod "AdtagLocationBeacon", '3.0-RC18'

	target 'QuickStartTests' do
		inherit! :search_paths
		# Pods for testing
	end

	target 'QuickStartUITests' do
		inherit! :search_paths
		# Pods for testing
	end
end
