# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'

platform :ios, '8.0'

target 'WelcomeNotification' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
  pod "ATLocationBeacon", '~> 2.7.3'
end
