# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'NotificationStrategyStarter' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod "ATConnectionHttp",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATConnectionHttp.git", :tag => "2.3.9"
  pod "ATAnalytics",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATAnalytics.git", :tag => "2.3.9"
  pod "ATLocationBeacon",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATLocationBeacon.git", :tag => "2.3.9"
  # Pods for NotificationStrategyStarter

  target 'NotificationStrategyStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotificationStrategyStarterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
