platform :ios, '8.0'

target 'NotificationStrategy' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod "ATConnectionHttp",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATConnectionHttp.git", :tag => "2.5.3"
  pod "ATAnalytics",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATAnalytics.git", :tag => "2.5.3"
  pod "ATLocationBeacon",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATLocationBeacon.git", :tag => "2.5.3"

  target 'NotificationStrategyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotificationStrategyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
