source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'

platform :ios, '8.0'

target 'NotificationComplete' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod "ATLocationBeacon", '~> 2.7'

  target 'NotificationCompleteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotificationCompleteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
