platform :ios, '8.0'

target 'NotificationComplete' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod "ATConnectionHttp",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATConnectionHttp.git", :tag => "2.5.8"
  pod "ATAnalytics",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATAnalytics.git", :tag => "2.5.8"
  pod "ATLocationBeacon",:git => "https://forge.adtag.eu/ConnecthingsSDK/ATLocationBeacon.git", :tag => "2.5.8"


  target 'NotificationCompleteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotificationCompleteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
