source 'https://github.com/CocoaPods/Specs.git'
source 'git@forge.adtag.eu:ConnecthingsSDK/Specs.git'

platform :ios, '8.0'

target 'NotificationStrategy' do
	use_frameworks!
	pod "ATLocationBeacon", '~> 2.7-RC0'

	target 'NotificationStrategyTests' do
		inherit! :search_paths
	end

	target 'NotificationStrategyUITests' do
		inherit! :search_paths
	end
end
