source 'https://github.com/CocoaPods/Specs.git'
source 'git@forge.adtag.eu:ConnecthingsSDK/Specs.git'

platform :ios, '8.0'

target 'NotificationStrategyComplete' do
	pod "ATLocationBeacon", '~> 2.7-RC0'
	
	target 'NotificationStrategyCompleteTests' do
		inherit! :search_paths
	end
	
	target 'NotificationStrategyCompleteUITests' do
		inherit! :search_paths
	end
end
