source 'https://github.com/CocoaPods/Specs.git'
source 'https://forge.adtag.eu/pub/Specs'

platform :ios, '9.0'

target 'Complete' do
	use_frameworks!
    swift_version = "4.0"
    pod 'AdtagLocationBeacon', '~> 3.0-RC3' 

	target 'CompleteTests' do
		inherit! :search_paths
	end

	target 'CompleteUITests' do
		inherit! :search_paths
	 end
end
